### ISSUE TITLE
Copyright pattern should be configurable

### ISSUE THREAD

**Issue by The-Compiler** [PCManticore/copyrite#2]
For example, I don't have the `(c)` in my project - from this [GPL page](https://www.gnu.org/licenses/gpl-howto.html):

> Always use the English word “Copyright”; by international convention, this is used worldwide, even for material in other languages. The copyright symbol “©” can be included if you wish (and your character set supports it), but it's not necessary. There is no legal significance to using the three-character sequence “(C)”, although it does no harm.

**Comment by PCManticore** [comment]
Fixed by https://github.com/PCManticore/copyrite/commit/222ae7243379f2450e517b1154bc574f7d0c1ace.

There are two options which you can use, one for customizing the notice format in any way you like. The second is for specifying markers for these copyright notices, which will be found and replaced with new ones.
